### ISSUE TITLE
Provide storing/loading wallet from an I/O stream

### ISSUE THREAD

**Issue by dr-orlovsky** [BP-WG/bp-wallet#11]
I think abstracting the way the data are stored should be a good thing to do. Something like a writer/reader object for save and load methods.

This is an alternative to https://github.com/BP-WG/bp-wallet/pull/10

**Comment by ghost** [comment]
@dr-orlovsky how about use [opendal](https://opendal.apache.org/) as storage service?
i have a own development branch that tested with it, it works seems ok

**Comment by dr-orlovsky** [comment]
Looks interesting. Never had any experience with opendal. Feel free to PR in your branch here
