### ISSUE TITLE
WalletCache API

### ISSUE THREAD

**Issue by oacdutra** [BP-WG/bp-wallet#12]
**Description**

We must create an API to facilitate access and update `WalletCache` data. 

Unlike the [Wallet](https://github.com/BP-WG/bp-wallet/issues/11), the caching layer needs more flexibility because in some contexts, like WASM (web browser, web extension, etc..), we cannot access data with blocking calls. 

For example, 

When we integrated the previous version of the RGB (0.10) on bitmask-core, we implemented all resolvers of RGB to store data in memory because the resolvers of the lib made blocking calls (I'm not sure if you remember, but we talked about it on devchat and I implemented [here](https://github.com/diba-io/bitmask-core/pull/173#issuecomment-1539561284)). I would like make the same with `Indexer` trait.

Also, we have better ways to retrieve information in context web-browser, like [websocket](https://github.com/mempool/mwck-rs).

**Comment by dr-orlovsky** [comment]
Can you elaborate a bit more on which specific changes we need?

**Comment by oacdutra** [comment]
> Can you elaborate a bit more on which specific changes we need?

We need a way to access all proprieties of the `WalletCache` outside of the crate. With this, I can write custom `Indexer` implementation to create or update data of the cache.

Also, we need change the `Wallet::update` method to verify if cache has already been created previously. If yes, it only updates the cache, otherwise it creates a new one.
