### ISSUE TITLE
Dependency of `bp-convert` is missing

### ISSUE THREAD

**Issue by yanganto** [BP-WG/bp-wallet#23]
`bp-convert` is not available, because there is no `primitives` branch in `bp-core` anymore.
https://github.com/BP-WG/bp-wallet/blob/0009dc615ff4c44420408663ed09de9ea5a2c2b7/convert/Cargo.toml#L25

**Comment by dr-orlovsky** [comment]
Closed in https://github.com/BP-WG/bp-wallet/commit/4543cc05bc7f4e5b80a1ac796ba72aac2a066de5
