### ISSUE TITLE
CLI: unknown variant tapretKey when finalizing a tapret PSBT

### ISSUE THREAD

**Issue by nicbus** [BP-WG/bp-wallet#58]
Trying to use bp-wallet via CLI in rgb-sandbox, I find that there's an issue when finalizing the PSBT for a tapret transfer.

The command `bp finalize -n regtest -d data0 -w wallet_0 psbt tx` yields:
```
Loading descriptor from wallet wallet_0 ... Error: unable to parse TOML file - TOML parse error at line 3, column 12
  |
3 | [generator.tapretKey]
  |            ^^^^^^^^^
unknown variant `tapretKey`, expected `wpkh` or `trKey`
```

I guess the error comes from parsing the wallet's `descriptor.toml` file. Here are the contents of `data0/regtest/wallet_0/descriptor.toml`:
```
network = "regtest"

[generator.tapretKey]
tr = "[a2f5c30b/86h/1h/0h]tpubDCQ9qLpMj1EnnwDx2CZqHu271tPLhgXFdB7LBp26gtxyFAhoHoxaLWByb4PM6ELRpxKQB4Cma6s8pWYKyZ1Y52wH9WkSxBwNqvCP2MyiUfe/<0;1;9;10>/*"

[generator.tapretKey.tweaks]
"&10/1" = "Jj7HrOiWFjNKkRnXw^(_bF#3Oq0&uKELWcx^kiFA00"
```

I tried to change the mentioned key and executing the command again yields:
```
Loading descriptor from wallet wallet_0 ... Error: unable to parse TOML file - TOML parse error at line 3, column 2
  |
3 | [generator.trKey]
  |  ^^^^^^^^^
wanted exactly 1 element, more than 1 element
```

**Comment by dr-orlovsky** [comment]
You are using `bp` command, while you need `rgb`. BP doesn't know anything RGB-specific, including tapret descriptors. Use `rgb finalize` and everything should work

**Comment by nicbus** [comment]
I initially looked for `bp-wallet`'s commands (`seed`, `derive`, `finalize`) exposed via `rgb-wallet` but I couldn't find them. I have switched to rgb master branch (commit `b2bc6a2`) but I still can't find the `finalize` command. I suppose this is a recent addition, can you give me a commit where it's available?

**Comment by dr-orlovsky** [comment]
You can use BP for `seed`, `derive` (which doesn't touch descriptors), but you should use `rgb` for all PSBT operations, since they work differently from bitcoin-only version. The `finalize` however somehow got missed, it's a bug. Closing this issue in favor of https://github.com/RGB-WG/rgb/issues/230
