### ISSUE TITLE
sync utxo bug

### ISSUE THREAD

**Issue by cymqqqq** [BP-WG/bp-wallet#65]
I try to use bp-wallet to sync the utxo here, I set the electrum URL to `blockstream.info:143`, then set `indexer = AnyIndexer::Electrum(Box::new(Client::new(ELECTRUM_URL).unwrap()))`. And then when I call wallet.update(indexer), the errors print out:
<img width="1511" alt="image" src="https://github.com/user-attachments/assets/e9b5f220-c488-4602-86f1-48921b29e4ee">
So it's a bug?

**Comment by dr-orlovsky** [comment]
it seems your electrum URL misses `https://` prefix. But I agree that instead of painc there should be a more verbose message

**Comment by dr-orlovsky** [comment]
Can you please try using master tip?
